# Generated by Django 6.1.1 on 2026-09-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_escaneopendiente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escaneopendiente',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='escaneopendiente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
