# Generated by Django 6.1.1 on 2026-09-22 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_escaneopendiente_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('dias_semana', models.CharField(default='0,1,2,3,4,5,6', max_length=20)),
                ('hora', models.TimeField(default='02:00')),
                ('max_respaldos', models.IntegerField(default=30)),
                ('incluir_media', models.BooleanField(default=False)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ConfiguracionRespaldo',
            },
        ),
        migrations.CreateModel(
            name='Respaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático')], default='MANUAL', max_length=20)),
                ('tamano_kb', models.FloatField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('exito', models.BooleanField(default=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('incluye_media', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Respaldo',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
